/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define    GPIOD_BASE          (uint32_t*)0x40020C00
#define    GPIOD_ODR           (uint32_t*)0x40020C14
#define    GPIO_PIN_RESET     0
#define    GPIO_PIN_SET       1


#define    INTERRUPT            (uint8_t*)86h
#define    PORT_B               (uint8_t*)06h


void delay(){
	for(int i=0;i<1000000;i++);
}

void gpioWritePin(uint32_t pinNo, uint32_t pinMode){

	*GPIOD_BASE |= (1<<2*pinNo);

	if(pinMode == GPIO_PIN_SET)
		*GPIOD_ODR |= (1u<<pinNo);
	else
		*GPIOD_ODR &= ~(1u<<pinNo);


}

void toggle(const int pin){
	volatile uint32_t *pGPIOBase = (uint32_t*)0x40020C00;
	*pGPIOBase |= (1<<2*pin);

	volatile uint32_t *pGPIODR = (uint32_t*)0x40020C14;
	*pGPIODR = *pGPIODR ^ (1u<<pin);
}

void writePin(int pin, int logic){
	volatile uint32_t *pGPIOBase = (uint32_t*)0x40020C00;
	*pGPIOBase |= (1u<<2*pin);

	volatile uint32_t *pGPIODR = (uint32_t*)0x40020C14;
	if(logic == 0)
		*pGPIODR &= ~(1u<<pin);
	else
		*pGPIODR |=  (1u<<pin);
}


int main(void){
    /* Loop forever */

	volatile uint32_t *pRCCAhb1Enr = (uint32_t*)0x40023830;
	*pRCCAhb1Enr |= (1u<<3);

	volatile uint32_t *pGPIOBase = (uint32_t*)0x40020C00;
	*pGPIOBase |= (1u<<24);
	*pGPIOBase |= (1u<<26);
	*pGPIOBase |= (1u<<28);
	*pGPIOBase |= (1u<<30);

	volatile uint32_t *pGPIODR = (uint32_t*)0x40020C14;
	*pGPIODR |= (1u<<12);
	*pGPIODR |= (1u<<13);
	*pGPIODR |= (1u<<14);
	*pGPIODR |= (1u<<15);



	gpioWritePin(13, 1);
	delay();
	gpioWritePin(13, 0);

	toggle(13);
	writePin(13, GPIO_PIN_SET);
	delay();
	writePin(13,GPIO_PIN_RESET);


}
